modLoader="javafml"
loaderVersion="${target_loader}"
issueTrackerURL="https://github.com/IMB11/SmartItemHighlight/issues"
displayURL="http://IMB11.dev/"
logoFile="assets/${mod_id}/icon.png"
authors="IMB11"
clientSideOnly = true
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="${loader}"
type="required"
versionRange="${target_loader}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mru"
type="required"
versionRange="${target_mru}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="${mod_id}.mixins.json"